In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\manika sharma\Downloads\placement.csv")

In [3]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [5]:
df = df.iloc[:,1:]

In [6]:
df.shape

(100, 3)

In [7]:
x = df.iloc[:,0:2]
y = df.iloc[:, -1]

In [8]:
x

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [9]:
y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: placement, Length: 100, dtype: int64

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.1)

In [11]:
x_train

    cgpa     iq
20   6.6  120.0
8    6.1  156.0
94   4.7   52.0
97   6.7  182.0
69   8.5  120.0
..   ...    ...
59   4.8  112.0
50   3.5  233.0
80   4.9  196.0
26   7.0  199.0
81   5.4  107.0

[90 rows x 2 columns]

In [12]:
y_train

20    1
8     0
94    0
97    1
69    1
     ..
59    0
50    0
80    0
26    1
81    0
Name: placement, Length: 90, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
x_train = scaler.fit_transform(x_train)

In [16]:
x_train

array([[ 0.54424724, -0.08806819],
       [ 0.11757258,  0.79534031],
       [-1.0771165 , -1.75672869],
       [ 0.62958218,  1.43335756],
       [ 2.16561098, -0.08806819],
       [-0.90644663,  0.25547956],
       [-0.22376716,  0.40271431],
       [ 1.31226165,  0.84441856],
       [ 0.03223764,  0.62356643],
       [-0.65044183,  0.20640131],
       [ 1.14159178, -0.92239844],
       [-0.65044183,  0.91803593],
       [ 1.39759658,  0.10824481],
       [-0.56510689, -0.23530294],
       [ 0.45891231, -2.12481557],
       [ 0.37357738, -0.18622469],
       [ 0.97092191,  0.67264468],
       [ 1.14159178, -1.80580694],
       [ 0.45891231,  0.15732306],
       [ 0.03223764,  0.01008831],
       [-0.90644663,  0.77080118],
       [ 1.22692671,  0.20640131],
       [ 0.11757258, -1.43772007],
       [ 0.28824244,  0.10824481],
       [-1.75979597, -0.35799857],
       [-0.90644663, -1.53587657],
       [ 1.82427125,  1.04073156],
       [-0.22376716,  0.20640131],
       [ 0.11757258,  0.20640131],
       [-1.0771165 , -0.06352907],
       [ 0.54424724,  0.35363606],
       [-0.73577676,  0.10824481],
       [ 0.28824244,  0.08370568],
       [ 0.88558698,  0.37817518],
       [ 0.11757258, -0.50523332],
       [ 1.39759658, -0.84878107],
       [-1.3331213 , -2.00211994],
       [ 1.73893632, -1.09417232],
       [-0.13843223,  1.04073156],
       [-1.3331213 ,  0.62356643],
       [-0.47977196,  0.28001868],
       [-0.99178156,  0.42725343],
       [ 1.31226165,  0.15732306],
       [-0.73577676,  1.28612281],
       [-0.65044183, -0.33345944],
       [ 1.14159178, -0.18622469],
       [ 0.88558698, -0.28438119],
       [-1.41845623,  1.87506181],
       [-0.65044183, -0.82424194],
       [-0.05309729, -0.43161594],
       [-1.16245143,  0.54994906],
       [ 0.03223764, -0.52977244],
       [-0.8211117 , -0.13714644],
       [ 0.20290751, -0.25984207],
       [-1.67446103, -0.57885069],
       [ 0.03223764, -1.92850257],
       [ 1.31226165, -1.53587657],
       [-0.90644663,  0.67264468],
       [ 0.03223764, -1.41318094],
       [-1.0771165 , -0.89785932],
       [-0.22376716,  1.11434893],
       [-1.67446103, -1.19232882],
       [ 0.45891231, -0.82424194],
       [-0.56510689, -0.06352907],
       [ 0.71491711, -0.82424194],
       [ 1.14159178,  0.32909693],
       [-0.99178156,  0.96711418],
       [-0.73577676, -1.41318094],
       [ 1.56826645, -0.23530294],
       [ 0.97092191, -1.85488519],
       [-0.22376716,  0.47633168],
       [-0.65044183,  2.4640008 ],
       [-0.8211117 , -1.48679832],
       [-0.99178156,  1.11434893],
       [ 0.71491711, -0.28438119],
       [-0.13843223,  0.45179256],
       [-2.27180557,  1.45789668],
       [-0.8211117 , -0.79970282],
       [ 0.28824244, -0.50523332],
       [ 1.82427125,  0.62356643],
       [ 0.88558698,  1.26158368],
       [ 1.99494112,  1.08980981],
       [ 0.80025205,  0.35363606],
       [ 0.37357738,  0.42725343],
       [ 0.80025205, -0.67700719],
       [-0.99178156, -0.28438119],
       [-2.1011357 ,  2.68485293],
       [-0.90644663,  1.77690531],
       [ 0.88558698,  1.85052268],
       [-0.47977196, -0.40707682]])

In [17]:
x_test = scaler.fit_transform(x_test)

In [18]:
x_test

array([[ 0.34853574,  1.25205015],
       [ 0.76677863, -0.01715137],
       [ 0.76677863,  0.60029802],
       [-1.18502152,  0.53169253],
       [-1.18502152, -0.32587607],
       [ 0.62736433,  1.04623369],
       [ 0.90619292,  0.53169253],
       [-1.882093  , -0.1200596 ],
       [ 1.04560722, -2.04101326],
       [-0.20912144, -1.45786661]])

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
clf = LogisticRegression()

In [21]:
clf.fit(x_train, y_train)

LogisticRegression()

In [22]:
y_pred = clf.predict(x_test)

In [23]:
y_test

38    1
0     1
43    1
12    0
41    0
74    1
60    1
22    0
64    1
78    0
Name: placement, dtype: int64

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test, y_pred)

1.0

In [26]:
import pickle

In [27]:
pickle.dump(clf,open('model.pkl','wb'))